### ISSUE TITLE
M64py flatpak crashes upon trying to open a rom

### ISSUE THREAD

**Issue by pizzadude** [flathub/net.sourceforge.m64py.M64Py#1]
Hi, M64py flatpak currently crashes when trying to open a rom. Here's the terminal output:

```
flatpak run net.sourceforge.m64py.M64Py
Qt: Session management error: Could not open network socket
M64Py version 0.3.0 (Linux 6.5.0-valve22-1-neptune-65-g9a338ed8a75e/Xcb)

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.6.0
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Using full mem base
Core: Unable to open rom database file '(null)'.
Frontend: INFO: video extension enabled
Input: Couldn't find config file 'InputAutoCfg.ini'
Input: Couldn't find config file 'InputAutoCfg.ini'
Input: missing 'plugged' parameter from config section AutoConfig0. Setting to 1 (true).
Input: missing config key 'DPad R' for controller 1 button 0
Input: missing config key 'DPad L' for controller 1 button 1
Input: missing config key 'DPad D' for controller 1 button 2
Input: missing config key 'DPad U' for controller 1 button 3
Input: missing config key 'Start' for controller 1 button 4
Input: missing config key 'Z Trig' for controller 1 button 5
Input: missing config key 'B Button' for controller 1 button 6
Input: missing config key 'A Button' for controller 1 button 7
Input: missing config key 'C Button R' for controller 1 button 8
Input: missing config key 'C Button L' for controller 1 button 9
Input: missing config key 'C Button D' for controller 1 button 10
Input: missing config key 'C Button U' for controller 1 button 11
Input: missing config key 'R Trig' for controller 1 button 12
Input: missing config key 'L Trig' for controller 1 button 13
Input: missing config key 'Mempak switch' for controller 1 button 14
Input: missing config key 'Rumblepak switch' for controller 1 button 15
Input: missing config key 'X Axis' for controller 1 axis 0
Input: missing config key 'Y Axis' for controller 1 axis 1
Core: Goodname: SUPER MARIO 64 (unknown rom)
Core: Name: SUPER MARIO 64      
Core: MD5: 20B854B239203BAF6C961B850A4A51A2
Core: CRC: 635A2BFF 8B022326
Core: Imagetype: .z64 (native)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
Frontend: INFO: using Video plugin: 'GLideN64' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.6.0
Core: Input plugin does not contain VRU support.
Core: input plugin did not specify a render callback; there will be no on screen display by the input plugin.
Input: 1 SDL joysticks were found.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/m64py/frontend/mainwindow.py", line 382, in on_rom_opened
    self.cheats = Cheat(self)
                  ^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/m64py/frontend/cheat.py", line 39, in __init__
    self.cheats = self.read_file()
                  ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/m64py/frontend/cheat.py", line 172, in read_file
    cheat_file = os.path.join(
                 ^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

Input: Couldn't find config file 'InputAutoCfg.ini'
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: No auto-config found for joystick named 'Microsoft X-Box 360 pad 0' in InputAutoConfig.ini
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: N64 Controller #1: Forcing default keyboard configuration
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: Couldn't find config file 'InputAutoCfg.ini'
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing 'plugged' parameter from config section AutoConfig0. Setting to 1 (true).
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'DPad R' for controller 1 button 0
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'DPad L' for controller 1 button 1
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'DPad D' for controller 1 button 2
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'DPad U' for controller 1 button 3
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'Start' for controller 1 button 4
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'Z Trig' for controller 1 button 5
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'B Button' for controller 1 button 6
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'A Button' for controller 1 button 7
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'C Button R' for controller 1 button 8
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'C Button L' for controller 1 button 9
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'C Button D' for controller 1 button 10
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'C Button U' for controller 1 button 11
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'R Trig' for controller 1 button 12
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'L Trig' for controller 1 button 13
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'Mempak switch' for controller 1 button 14
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'Rumblepak switch' for controller 1 button 15
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'X Axis' for controller 1 axis 0
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: missing config key 'Y Axis' for controller 1 axis 1
Exception ignored on calling ctypes callback functionException ignored in sys.unraisablehookInput: 1 controller(s) found, 1 plugged in and usable in the emulator
QThread: Destroyed while thread is still running

```

**Comment by pizzadude** [comment]
I fixed it by adding "/app/share/mupen64plus" to the "Data directory" field in Paths settings. It seems the flatpak doesn't come pre-configured with the correct data directory.

**Comment by gen2brain** [comment]
Thanks for reporting. Yes, that worked, and while I was making changes to be accepted I broke it.

**Comment by gen2brain** [comment]
Fixed in https://github.com/flathub/net.sourceforge.m64py.M64Py/pull/2.
